// Copies the files the engine needs from the project into engine/public/ (Remotion's static folder),
// and writes src/generated/episodes.ts so every episode gets its own composition.
// Sources stay where they are (brand/, assets/, episodes/); public/ is a disposable build copy.
import { cpSync, existsSync, mkdirSync, readdirSync, rmSync, statSync, writeFileSync } from "node:fs";
import { dirname, extname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const ENGINE = join(dirname(fileURLToPath(import.meta.url)), "..");
const ROOT = join(ENGINE, "..");
const PUBLIC = join(ENGINE, "public");

// Only web-usable formats; skips design sources (psd, eps, pdf, zip).
const ALLOWED = new Set([".svg", ".png", ".jpg", ".jpeg", ".webp", ".mp3", ".wav", ".m4a", ".json", ".yaml", ".md"]);
const SOURCES = ["brand/bytesized/svg", "brand/back-in-a-gist", "brand/design-language/tokens.json", "assets", "episodes"];

function copyTree(src) {
  const abs = join(ROOT, src);
  if (!existsSync(abs)) return 0;
  if (statSync(abs).isFile()) {
    if (!ALLOWED.has(extname(abs).toLowerCase())) return 0;
    const dest = join(PUBLIC, src);
    mkdirSync(dirname(dest), { recursive: true });
    cpSync(abs, dest);
    return 1;
  }
  let n = 0;
  for (const entry of readdirSync(abs)) {
    if (entry.startsWith(".") || entry === "storyboard" || entry === "out") continue; // review and render output, not inputs
    n += copyTree(join(src, entry));
  }
  return n;
}

rmSync(PUBLIC, { recursive: true, force: true });
mkdirSync(PUBLIC, { recursive: true });
const copied = SOURCES.reduce((n, s) => n + copyTree(s), 0);

const slugs = readdirSync(join(ROOT, "episodes"))
  .filter((d) => existsSync(join(ROOT, "episodes", d, "episode.yaml")))
  .sort();
mkdirSync(join(ENGINE, "src/generated"), { recursive: true });
writeFileSync(
  join(ENGINE, "src/generated/episodes.ts"),
  `// Generated by scripts/sync-public.mjs. Do not edit.\nexport const EPISODE_SLUGS = ${JSON.stringify(slugs, null, 2)} as const;\n`,
);

console.log(`synced ${copied} files → ${relative(ROOT, PUBLIC)}/ · episodes: ${slugs.join(", ") || "none"}`);
